/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as SignToVoiceRouteImport } from './routes/sign-to-voice'
import { Route as VoiceToSignRouteImport } from './routes/voice-to-sign'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const SignToVoiceRoute = SignToVoiceRouteImport.update({
  id: '/sign-to-voice',
  path: '/sign-to-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceToSignRoute = VoiceToSignRouteImport.update({
  id: '/voice-to-sign',
  path: '/voice-to-sign',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LearnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn': typeof LearnRouteWithChildren
  '/sign-to-voice': typeof SignToVoiceRoute
  '/voice-to-sign': typeof VoiceToSignRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-to-voice': typeof SignToVoiceRoute
  '/voice-to-sign': typeof VoiceToSignRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn': typeof LearnRouteWithChildren
  '/sign-to-voice': typeof SignToVoiceRoute
  '/voice-to-sign': typeof VoiceToSignRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learn'
    | '/sign-to-voice'
    | '/voice-to-sign'
    | '/learn/$slug'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-to-voice' | '/voice-to-sign' | '/learn/$slug' | '/learn'
  id:
    | '__root__'
    | '/'
    | '/learn'
    | '/sign-to-voice'
    | '/voice-to-sign'
    | '/learn/$slug'
    | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnRoute: typeof LearnRouteWithChildren
  SignToVoiceRoute: typeof SignToVoiceRoute
  VoiceToSignRoute: typeof VoiceToSignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-to-voice': {
      id: '/sign-to-voice'
      path: '/sign-to-voice'
      fullPath: '/sign-to-voice'
      preLoaderRoute: typeof SignToVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-to-sign': {
      id: '/voice-to-sign'
      path: '/voice-to-sign'
      fullPath: '/voice-to-sign'
      preLoaderRoute: typeof VoiceToSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof LearnRoute
    }
  }
}

interface LearnRouteChildren {
  LearnSlugRoute: typeof LearnSlugRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnSlugRoute: LearnSlugRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnRoute: LearnRouteWithChildren,
  SignToVoiceRoute: SignToVoiceRoute,
  VoiceToSignRoute: VoiceToSignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
